---
admin_users_sudo_group: wheel
webserver_docroot: /usr/share/nginx/html
webserver_firewall_backend: firewalld
sshd_sftp_subsystem: /usr/lib/openssh/sftp-server

rhsm_auth_method: activation_key
rhsm_org_id: "{{ vault_rhsm_org_id }}"
rhsm_activation_key: "{{ vault_rhsm_activation_key }}"

# Example: enable the standard RHEL 9 base and appstream repos
rhsm_repositories:
  - rhel-10-for-x86_64-baseos-rpms
  - rhel-10-for-x86_64-appstream-rpms
