---
- name: Restart PostgreSQL
  ansible.builtin.service:
    name: "{{ postgres_service }}"
    state: restarted

- name: Reload PostgreSQL
  ansible.builtin.service:
    name: "{{ postgres_service }}"
    state: reloaded
