---
postgres_version: 18
postgres_databases: []
postgres_users: []
postgres_allowed_hosts: []
postgres_packages:
  - postgresql-{{ postgres_version }}
  - postgresql-contrib
  - python3-psycopg2
postgres_service: "postgresql@{{ postgres_version }}-main"
postgres_language_pack: language-pack-en
postgres_initdb_locale: en_US.utf8
postgres_config_dir: "/etc/postgresql/{{ postgres_version }}/main"
postgres_conf_file: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
postgres_hba_file: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
postgres_admin_user: postgres
postgres_listen_addresses: "'*'"
