---
postgres_version: 16
postgres_databases: []
postgres_users: []
postgres_allowed_hosts: []
postgres_packages:
  - postgresql
  - postgresql-contrib
  - python3-psycopg2
postgres_admin_user: postgres
postgres_listen_addresses: "'*'"
