---
- name: Instal PostgreSQL packages
  ansible.builtin.package:
    name: "{{ postgres_packages }}"
    state: present

- name: Initialise the database cluster (RHEL only)
  ansible.builtin.command:
    cmd: "/usr/pgsql-{{ postgres_version }}/bin/postgresql-{{ postgres_version }}-setup initdb"
    creates: "{{ postgres_config_dir }}/PG_VERSION"
  when: postgres_needs_initdb | bool

- name: Ensure PostgreSQL service is enabled and running
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: started

- name: Set listen_addresses in postgreslq.conf
  ansible.builtin.lineinfile:
    path: "{{ postgres_conf_file }}"
    regexp: "^#?listen_addresses"
    line: "listen_addresses = {{ postgres_listen_addresses }}"
    state: present
  notify: Restart PostgreSQL

- name: Configure pg_hba.conf (client auth)
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ postgres_hba_file }}"
    owner: postgres
    group: postgres
    mode: "0640"
  notify: Reload PostgreSQL

- name: Create application databases
  community.general.postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('UTF8') }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF8') }}"
    state: present
  loop: "{{ postgres_databases }}"
  loop_control:
    label: "{{ item.name }}"
  become: true
  become_user: "{{ postgres_admin_user }}"

- name: Create database users
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
  loop: "{{ postgres_users }}"
  loop_control:
    label: "{{ item.name }}"
  become: true
  become_user: "{{ postgres_admin_user }}"
  no_log: true # never print passwords in task output or Semaphore logs

- name: Grant database privileges to users
  community.general.postgresql_user:
    database: "{{ priv_item.1 }}"
    roles: "{{ priv_item.0.name }}"
    privs: "{{ priv_item.0.privs }}"
    type: database
    state: present
  # flatten user+database combination into one loop
  loop: "{{ postgres_users | subelements('databases') }}"
  loop_control:
    loop_var: priv_item
    label: "{{ ptiv_item.0.name }} -> {{ priv_item.1 }}"
  become: true
  become_user: "{{ postgres_admin_user }}"
  no_log: true
